import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Noto_Sans_Tamil } from "next/font/google";
import { getLocale } from "next-intl/server";
import { hasSession } from "@/features/auth";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { HashScroll } from "@/components/layout/hash-scroll";
import { SplashScreen } from "@/components/layout/splash-screen";
import { ScrollToTop } from "@/components/layout/scroll-to-top";
import { PolicyNotice } from "@/components/layout/policy-notice";
import { JoinInvite } from "@/components/layout/join-invite";
import { AppProviders } from "@/lib/providers/app-providers";
import { LocaleProvider } from "@/lib/providers/locale-provider";
import { isLocale, defaultLocale } from "@/i18n/config";
import { siteConfig } from "@/config/site";
import "./globals.css";

/**
 * One typeface, used across the whole site. The variable axis lets headings go
 * to 800 and body text sit at 400 without loading extra files.
 */
const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
  // Real italics for the display accent — never a synthesised oblique.
  style: ["normal", "italic"],
  display: "swap",
});

/**
 * Plus Jakarta Sans covers no Tamil glyphs, so Tamil text needs its own face.
 * It sits after Jakarta in the font stack (see globals.css): Latin renders in
 * Jakarta, Tamil glyphs fall through to this — no per-locale switching needed.
 */
const notoTamil = Noto_Sans_Tamil({
  variable: "--font-noto-tamil",
  subsets: ["tamil"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: `${siteConfig.name} — ${siteConfig.tagline}`,
    // A page's own `title` fills the %s slot.
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  openGraph: {
    type: "website",
    siteName: siteConfig.name,
    title: `${siteConfig.name} — ${siteConfig.tagline}`,
    description: siteConfig.description,
    url: siteConfig.url,
  },
  // og:image / twitter:image are generated by app/opengraph-image.tsx.
  twitter: {
    card: "summary_large_image",
    title: `${siteConfig.name} — ${siteConfig.tagline}`,
    description: siteConfig.description,
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const resolved = await getLocale();
  const locale = isLocale(resolved) ? resolved : defaultLocale;
  const loggedIn = await hasSession();

  return (
    // next-themes writes the theme class on <html> before paint, which the
    // server cannot know about — so hydration differences here are expected
    <html
      lang={locale}
      className={`${jakarta.variable} ${notoTamil.variable} h-full`}
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col bg-canvas">
        {/* Scroll-reveal content must never be invisible without JavaScript */}
        <noscript>
          <style>{`.reveal{opacity:1!important;transform:none!important}`}</style>
        </noscript>

        <LocaleProvider initialLocale={locale}>
          <AppProviders>
            <SplashScreen />
            <HashScroll />
            <Header loggedIn={loggedIn} />
            <main className="flex-1">{children}</main>
            <Footer />
            <ScrollToTop />
            <PolicyNotice />
            <JoinInvite />
          </AppProviders>
        </LocaleProvider>
      </body>
    </html>
  );
}
